services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  ITplusX\HeadlessContainer\:
    resource: '../Classes/*'
    public: true

  ITplusX\HeadlessContainer\DataProcessing\ContainerProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'container'
